name: python-flake8
description: "Run flake8 python code linting"
branding:
  icon: check-circle
  color: green
inputs:
  checkName:
    description: "The name of the check to add annotations to.
      Generally the same as the job that uses this action"
    required: true
  isTest:
    description: "Used for internal tests."
  path:
    description: "Path to use for flake8"
    default: .
runs:
  using: "node12"
  main: "dist/index.js"
